networks:
  default:
    name: tg

volumes:
  tg-pg:
  tg-grafana:
  tg-prom:

services:
  postgres:
    container_name: tg-pg
    image: postgres:16.4
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_DB: 'tg-db'
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - tg-pg:/var/lib/postgresql/data
  
  loki:
    container_name: "tg-loki"
    image: grafana/loki
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yml:/etc/loki/local-config.yml
    command: --config.file=/etc/loki/local-config.yml
    restart: unless-stopped

  grafana:
    container_name: "tg-grafana"
    image: grafana/grafana:9.1.7
    restart: unless-stopped
    environment:
      GF_INSTALL_PLUGINS: 'grafana-clock-panel,grafana-simple-json-datasource'
    ports:
      - '3000:3000'
    volumes:
      - tg-grafana:/var/lib/grafana
  
  prometheus:
    container_name: 'tg-prom'
    image: prom/prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - tg-prom:/prometheus
    extra_hosts:
      - "host.docker.internal:host-gateway"
  
  jaeger:
    container_name: 'tg-jaeger'
    image: 'jaegertracing/all-in-one:latest'
    restart: unless-stopped
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - '4318:4318'
      - '4317:4317'
      - '16686:16686'
      - '14268:14268'
      - '9411:9411'