scrape_configs:
  - job_name: tgposter-scrape
    scrape_interval: 10s
    scrape_timeout: 5s
    static_configs:
      - targets: ['host.docker.internal:5059','host.docker.internal:5000']
        labels:
          app: tgposter-local
      - targets:
          - tgposter-api:8070
        labels:
          app: tgposter-api-docker
      - targets:
          - tgposter-worker:8090
        labels:
          app: tgposter-worker-docker