name: Build and deploy infrastructure

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Upload docker-compose.infra.yml
        uses: actions/upload-artifact@v4
        with:
          name: docker-compose-infra
          path: docker/docker-compose.infra.yml

      - name: Upload loki-config.yml
        uses: actions/upload-artifact@v4
        with:
          name: loki-config
          path: docker/loki-config.yml

      - name: Upload prometheus.yml
        uses: actions/upload-artifact@v4
        with:
          name: prometheus
          path: docker/prometheus.yml
  
  deploy:
    needs: [ build ]
    runs-on: [ self-hosted, runner ]
    
    steps:
      - name: Download prometheus.yml
        uses: actions/download-artifact@v4
        with:
          name: prometheus

      - name: Download docker-compose.infra.yml
        uses: actions/download-artifact@v4
        with:
          name: docker-compose-infra

      - name: Download loki-config.yml
        uses: actions/download-artifact@v4
        with:
          name: loki-config

      - name: Create .env file
        run: |
          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> .env
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env

      - name: Pull infrastructure stack and deploy
        run: |
          docker compose -f docker-compose.infra.yml pull
          docker compose -f docker-compose.infra.yml up -d