name: Build and deploy hosted

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push tgposter-worker
        uses: docker/build-push-action@v5
        with:
          context: .
          file: TgPoster.Worker/Dockerfile
          push: true
          tags: ghcr.io/evilvegetarian/tgposter-worker:latest

      - name: Upload docker-compose.worker.yml
        uses: actions/upload-artifact@v4
        with:
          name: docker-compose-worker
          path: docker/docker-compose.worker.yml
  
  deploy-worker:
    needs: [ build ]
    runs-on: [ self-hosted, runner ]
    
    steps:
      - name: Download docker-compose.worker.yml
        uses: actions/download-artifact@v4
        with:
          name: docker-compose-worker

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull latest image and restart container
        run: |
          export CONNECTIONSTRING='${{ secrets.CONNECTIONSTRING }}'
          export TELEGRAM_API_ID='${{ secrets.API_ID }}'
          export TELEGRAM_API_HASH='${{ secrets.API_HASH }}'
          export TELEGRAM_PHONE_NUMBER='${{ secrets.PHONE_NUMBER }}'
          export TELEGRAMOPTIONS_SECRETKEY='${{ secrets.TELEGRAMOPTIONS_SECRETKEY }}'
          export OPENROUTEROPTIONS_SECRETKEY='${{ secrets.OPENROUTEROPTIONS_SECRETKEY }}'
          export S3OPTIONS_ACESSKEY='${{ secrets.S3OPTIONS_ACESSKEY }}'
          export S3OPTIONS_SECRETKEY='${{ secrets.S3OPTIONS_SECRETKEY }}'
          export S3OPTIONS_SERVICEURL='${{ secrets.S3OPTIONS_SERVICEURL }}'
          export S3OPTIONS_BUCKETNAME='${{ secrets.S3OPTIONS_BUCKETNAME }}'
          docker compose -f docker-compose.worker.yml pull
          docker compose -f docker-compose.worker.yml up -d

      - name: Clean up old docker images and containers
        if: always()
        run: |
          docker container prune -f
          docker image prune -a -f